# Site settings
title: Processism - A Methodology for Pattern Discovery
description: An exploration of recurring patterns across domains of human knowledge
url: https://processism.wiki
baseurl: ""

# Build settings
markdown: kramdown

# Navigation structure
nav_enabled: true
nav_sort: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - foundational-framework-mission.md

# Additional settings
timezone: UTC
encoding: utf-8

# Permalinks
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "simple"