# Site settings
title: Processism
description: A philosophical framework for understanding reality through processes, interactions, and recursion
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://processism.wiki" # the base hostname & protocol

# Theme settings
remote_theme: pages-themes/minimal@v0.2
show_downloads: false

# Author information
author:
  name: Your Name
  email: your-email@example.com

# Social media (optional)
twitter:
  username: your-twitter-handle

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Collections (if you decide to use them later)
# collections:
#   principles:
#     output: true
#     permalink: /:collection/:name

# Defaults (for front matter)
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
