# Site settings
title: Processism - Reality's Fundamental Patterns
description: Discovery of three universal patterns through AI analysis of human knowledge. Complementarity, self-reference, and scale-invariance explained.
tagline: Three patterns that explain everything, including their own discovery
url: https://processism.wiki
baseurl: ""

# Theme - for GitHub Pages deployment:
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Site structure
collections:
  pages:
    output: true
    permalink: /:name

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Just the Docs theme settings
search_enabled: false
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/processism/processism.github.io"

# Footer content
footer_content: "This work is completely free. No rights reserved. No attribution needed."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme
color_scheme: light

# Google Analytics (add your own ID)
# ga_tracking: UA-XXXXXXXXX-X

# SEO settings
author:
  name: Processism
  email: processism@pm.me

# Default meta tags for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/processism-social.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO tag settings
twitter:
  username: processism
  card: summary

social:
  name: Processism
  links:
    - https://github.com/processism/processism.github.io
