# Site settings
title: Processism
description: A framework focusing on processes, interactions, and recursion
url: "https://processism.wiki"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima

# Theme customization
minima:
  date_format: "%b %-d, %Y"

# Plugins
plugins:
  - jekyll-seo-tag
