# Streamlined site settings
title: Processism
description: A framework focusing on processes, interactions, and recursion
url: "https://processism.wiki"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima

# Date format
minima:
  date_format: "%b %-d, %Y"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default layouts
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Include necessary files
include:
  - _pages
  - docs

# Essential plugins
plugins:
  - jekyll-seo-tag

# Math rendering
kramdown:
  math_engine: mathjax