# Site settings
title: A Methodology for Pattern Discovery
description: An empirical approach to identifying fundamental patterns across domains of human knowledge
url: https://processism.wiki
baseurl: ""

# Build settings
markdown: kramdown
theme: none

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
