# Site settings
title: Processism
description: A methodology for pattern discovery across domains of human knowledge
url: https://processism.wiki
baseurl: ""

# Theme - for GitHub Pages deployment:
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Site structure
collections:
  pages:
    output: true
    permalink: /:name

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Just the Docs theme settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/processism/processism.github.io"

# Footer content
footer_content: "Copyright &copy; 2025 Processism. Content licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme
color_scheme: light

# Google Analytics (add your own ID)
# ga_tracking: UA-XXXXXXXXX-X

# SEO settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/processism-social.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO tag settings
twitter:
  username: processism
  card: summary

social:
  name: Processism
  links:
    - https://github.com/processism/processism.github.io